DROP DATABASE IF EXISTS school1;
CREATE DATABASE school1;
CREATE SCHEMA school;
create table school.groups (group_id serial PRIMARY KEY, group_name character(50)  NOT NULL);
create table school.students (student_id serial PRIMARY KEY, group_id int,	first_name character(50)  NOT NULL,	last_name character(50) NOT NULL);
create table school.courses (course_id serial PRIMARY KEY,	course_name character(50)  NOT NULL,	course_description character(150));
create table school.students_courses (students_courses_id serial PRIMARY KEY, course_id int  NOT NULL ,  student_id int  NOT NULL); 
