CREATE SCHEMA school;
create table school.groups (group_id serial PRIMARY KEY, group_name character(50)  NOT NULL);
create table school.students (student_id serial PRIMARY KEY, group_id int,	first_name character(50)  NOT NULL,	last_name character(50) NOT NULL);
create table school.courses (course_id serial PRIMARY KEY,	course_name character(50)  NOT NULL,	course_description character(150));
create table school.students_courses (students_courses_id serial PRIMARY KEY, course_id int  REFERENCES school.courses ON DELETE CASCADE,  student_id int REFERENCES school.students ON DELETE CASCADE);
insert into school.groups (group_id, group_name) values (1,'gr1');
insert into school.groups (group_id, group_name) values (2,'gr2');
insert into school.groups (group_id, group_name) values (3,'gr3');
insert into school.students (student_id, first_name, last_name, group_id) values (1,'Nina','Ivanova', 1);
insert into school.students (student_id, first_name, last_name, group_id) values (2,'Nona','Petrova', 1);
insert into school.students (student_id, first_name, last_name, group_id) values (3,'Igor','Beliy', 3);
insert into school.courses (course_id, course_name) values (1, 'maths');
insert into school.courses (course_id, course_name) values (2, 'art');
insert into school.students_courses ( student_id, course_id ) values (1,1);
insert into school.students_courses ( student_id, course_id ) values (2,1);
insert into school.students_courses ( student_id, course_id ) values (3,2);